version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: aleksup/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    image: aleksup/foodgram_frontend
    env_file: .env
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: aleksup/foodgram_gateway
    env_file: .env
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
      - static:/var/www/static/
      - media:/var/www/media/
