version: '3.8'

services:
  web:
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app/
      - ./data/:/usr/src/app/data/
    ports:
      - 8001:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
volumes:
  postgres_data:
  test_data:
