version: '3'

volumes:
  pg_data:
  backend_static:
  frontend_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env.dev
    depends_on:
      - db
    volumes:
      - backend_static:/app/static/
      - media:/app/media/
      - ./data/:/app/data/

  frontend:
    env_file: .env.dev
    build: ./frontend/
    volumes:
      - frontend_static:/static
    command: cp -r /app/build/. /static/

  gateway:
    build: ./gateway/
    env_file: .env.dev
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - frontend_static:/var/www/frontend/
      - backend_static:/var/www/backend/
      - media:/var/www/media/
