version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13
    env_file: ../.env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/
    env_file: ../.env.dev
    volumes:
      - ../backend:/app
      - backend_static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend/
    volumes:
      - frontend_static:/app/result_build/build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/var/html/static/
      - media:/var/html/media/
