# Generated by Django 3.2.3 on 2024-01-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240113_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'ингредиенты для рецепта'},
        ),
    ]
